openapi: "3.0.0"
info:
  version: 1.0.0
  title: Turtle Guide API
  description: The API of the Project Turtle Guide
  termsOfService: http://swagger.io/terms/
  contact:
    name: Turtles Team
    email: api@turtles-team.io
    url: http://turtles-team.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://http://localhost:5000/api
paths:
  /guides:
    get:
      description: Returns all the guides created by the owner. It gets the owner from the token.
      operationId: getGuide
      security:
        - bearerAuth: []
      responses:
        "200":
          description: guide response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuideAdd"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Invalid Token Response
          content:
            application/json:
              schema:
                $ref: "#/components/responses/UnauthorizedError"
    post:
      description: Creates a new guide.
      operationId: addGuide
      requestBody:
        description: Guide to add to the exhibitor.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Guide"
      responses:
        "200":
          description: pet response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuideAdd"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /users:
    get:
      description: Route to manage users
      responses:
        "200":
          description: OK
  /auth:
    get:
      responses:
        "200":
          description: OK
components:
  schemas:
    AllData:
      allOf:
        - $ref: "#/components/schemas/Data"
        - type: array
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
    Data:
      type: object
      required:
        - token
      properties:
        success:
          type: boolean
        data:
          type: array
        allOf:
          $ref: "#/components/schemas/Guide"
          type: object
    GuideAdd:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: "#/components/schemas/Guide"
    Guide:
      type: object
      required:
        - nameIdentifier
        - title
        - description
        - account
      properties:
        nameIdentifier:
          type: string
        title:
          type: string
        description:
          type: string
        sections:
          type: array
        menuOne:
          type: array
        menuTwo:
          type: array
        account:
          type: object
    NewPet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              code:
                type: integer
                format: int32
              message:
                type: string
              error:
                type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
